### ISSUE TITLE
Browser binary path

### ISSUE THREAD

**Issue by SomeWhereSomeHow** [titusfortner/webdrivers#103]
#### Summary
Having multiple browsers/versions creates issue duo to the way the binary path is checked/set. Since setting the binary path with:

`Selenium::WebDriver::Chrome.path = '/chromium/install/path/to/binary'`

it makes it globally for all other browsers as well. Hence testing with multiple browser and versions is not really supported. The arguments set while registering a browser are also not taken if the path is set this way. 

So instead of setting the binary path globally, each session instance should be checked for it's binary path, if it isn't set there, a fallback to the default can be done.

```
Capybara::Selenium::Driver.new(
  ...
  options: Selenium::WebDriver::Chrome::Options.new(
    binary: '/chromium/install/path/to/binary'
  ),
  ...
)
```

See referenz [here](https://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/Chrome/Options.html)

If anything is unclear or I'm missing something feel free to ask.

#### Debug Info
Running macOS Mojave 10.14.4

Testframework: RSpec (3.8.0) with Capybara(3.14.0) (I need to update, I know!)

- Chrome - 74.0.3729.131 
- ChromeBeta - 75.0.3770.18 beta
- Firefox - 66.0.3
- Firefoxbeta - 67.0b16
- FirefoxESR60 - 60.6.1
- FirefoxESR52 - 52.9.0

#### Expected Behavior

Each requested session is checked for it's own binary path, driver is loaded for this specific browser version.

**Comment by titusfortner** [comment]
Being able to store that value in the Options class is necessary when you need to pass that information via capabilities JSON to a remote session, and shouldn't be needed if you are executing on a local machine, since the value is processed in only one place and in the same scope as the initialization.

So, I'm confused as to how you will know where to set the binary in the capabilities, but would not know how to set the path instead. Couldn't you just as easily do:

```
Selenium::WebDriver::Chrome.path = '/chromium/install/path/to/binary'
Capybara::Selenium::Driver.new(
  ...
  options: Selenium::WebDriver::Chrome::Options.new(
   ...
  ),
  ...
)
```

We could probably implement something like this, but I'm not seeing why it would be necessary:

```
  options: Selenium::WebDriver::Chrome::Options.new(
       binary: proc { ::Webdrivers::Chromedriver.update('/chromium/install/path/to/binary') }
  ),
```

**Comment by SomeWhereSomeHow** [comment]
I have tried your approach already, but since the `Selenium::WebDriver::Chrome.path = '/chromium/install/path/to/binary'` is shared between all drivers, which causes the setting to be overwritten if I register a second chrome. 

The reason I have to pass the binary when executing locally is because I have chrome and chromebeta installed and hence the binary has to be specified. When executing remotely, I won't need it since my selenium-hub (or rather the nodes) knows where the binarys on the remote machine are. 

So here my code for registering the driver:

```
    Capybara.register_driver driver_name do |app|
      Selenium::WebDriver::Chrome.path = '/chromium/install/path/to/binary' # <- your proposal
      Capybara::Selenium::Driver.new(
        app,
        browser: :chrome,
        desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
          acceptInsecureCerts: true,
          chromeOptions: {
            args: @@local_chrome_args,
            binary: binary_path
          }
        )
      )
    end
```

To give a little context, I register multiple browser and versions before any test is executed and then use those registered drivers multiple times in mixed order.

A workaround for me would be to reregister a browser before each test, which would overwrite the setting all the time, but not seeing any advantage there. 

Hope this clarifies the issue.

**Comment by titusfortner** [comment]
Oh, right, Capybara's driver registrations are lazy loading. In order to use Capybara remotely in parallel the way I recommend to users, I actually do set it to re-register the driver before every test (https://github.com/saucelabs-sample-test-frameworks/Ruby-RSpec-Capybara/blob/master/spec/spec_helper.rb#L16).

@twalpole this is why I prefer explicit driver initialization over driver registrations. :) What do you think about webdrivers implementing `#update` to take an optional `browser_path` parameter like I suggested above, or do you have another idea?

**Comment by twalpole** [comment]
The reality here is that this use-case (ie. two different versions of chromedriver being used at the same time) isn't a currently supported use-case (wasn't for `chromedriver-helper` either).  @titusfortner I believe Your currently suggested solution would involve it repeatedly downloading different versions of chromedriver as it swapped between different browsers.  The only current solution I see  for this is for the OP to remove `webdrivers` from their project currently, download the needed drivers themself, and pass the relevant chromedriver and chrome binary locations in their respective driver registrations.  It would be possible to do something about this for v4 if we updated webdrivers to  have multiple versions of a specific driver downloaded at the same time (store each version in it's own directory under the install dir or something.  Also, I don't really see how explicit driver initialization would help here - it'd still be swapping back and forth (and re-downloading) between drivers all the time.

**Comment by twalpole** [comment]
And just in case OP doesn't know how to specify the driver location, it would be something like

```
Capybara.register_driver driver_name do |app|
  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    service: ::Selenium::WebDriver::Service.chrome(path: '/path/to/version/of/chromedriver'),
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.chrome(
      acceptInsecureCerts: true,
      chromeOptions: {
        args: @@local_chrome_arg,
        binary: '/path/to/chrome/binary'
      }
    )
  )
end
```

**Comment by titusfortner** [comment]
I guess I was thinking of the scenario when they were usually the same version and just needed to verify. Different versions at the same time would cause all kinds of interesting collisions. This wouldn't have been an issue when the same driver could support multiple versions of browsers, or you just want to always have the "latest" version of the driver. 

Another option is that you can specify the version of driver you want, and it will be used for all browsers on the system without checking for browser versions. You'll just have to ensure that your browsers are in synch and do not update, etc.

```
Webdrivers::Chromedriver.required_version = '73.0.3683.20'
```

It might be easier to manage the drivers manually the way Thomas described.

**Comment by SomeWhereSomeHow** [comment]
Thanks for your time and thoughts on this, so I guess I have to manage the drivers manually. Keep up the good work and maybe you think about giving my use case a chance, since testing against multiple versions of browser is quite common.

**Comment by twalpole** [comment]
@SomeWhereSomeHow Testing against multiple versions isn't the issue, it's testing against multiple versions of the browser within the same test run that causes the issue.  If it was just doing multiple test runs, each with a different browser version that's easily handled by setting a separate install directory for each run.
