### ISSUE TITLE
Rubygems warning in 3.9

### ISSUE THREAD

**Issue by brenogazzola** [titusfortner/webdrivers#107]
#### Summary
After update to version 3.9 launching the browser results in a warning from Rubygems.

#### Debug Info
Please provide the following information for bug reports:

* Operating system / CI Environment: Ubuntu 18.04
* Browser and version: Chrome Latest

#### Expected Behavior
No warning messages

#### Actual Behavior
Launching the browser results in a `nil versions are discouraged and will be deprecated in Rubygems 4` warning.

**Comment by twalpole** [comment]
Ugh -- This is coming from `normalize_version` when nil is passed in -- we could just change it to call `Gem::Version(version.to_s)` which would produce a version of 0 for nil (rather than a blank version)- just need to make sure that wouldn't be an issue

**Comment by titusfortner** [comment]
yeah, let me make sure we are handling these appropriately everywhere... I must have missed one (or more)

**Comment by titusfortner** [comment]
fixed: 2197d869f4bcff036ed4c288a1a3f31b4cb011db
