### ISSUE TITLE
Introduce method to get driver hosts to be ignored by VCR, WebMock

### ISSUE THREAD

**Issue by eliotsykes** [titusfortner/webdrivers#109]
Consider adding a method to webdrivers to return all of the driver hosts that ought to be ignored by testing tools like VCR and WebMock.

This would simplify the supporting config as follows:

```diff
VCR.configure do |config|
  config.ignore_hosts(
-    "chromedriver.storage.googleapis.com",
-    "github.com/mozilla/geckodriver/releases",
-    "selenium-release.storage.googleapis.com",
-    "developer.microsoft.com/en-us/microsoft-edge/tools/webdriver"
+    *Webdrivers.driver_hosts
  )
end
```

```diff
-WebMock.disable_net_connect!(allow_localhost: true, allow: [
-  "https://chromedriver.storage.googleapis.com",
-  "https://github.com/mozilla/geckodriver/releases",
-  "https://selenium-release.storage.googleapis.com",
-  "https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver"
-])
+WebMock.disable_net_connect!(allow_localhost: true, allow: Webdrivers.driver_hosts)
```

This code was modified from the code provided at https://github.com/titusfortner/webdrivers/wiki/Using-with-VCR-or-WebMock

**Comment by titusfortner** [comment]
Well, they aren' t currently public methods, but you could:
```
Webdrivers::Chromedriver.send(:base_url)
```
Especially now that you can require only the drivers you want to use, I'm not sure it makes sense for the project to roll this up into a single method...

**Comment by eliotsykes** [comment]
Thanks thats interesting. So you can get all of the `base_url`s with:

```rb
# With activesupport gem
driver_urls = Webdrivers::Common.subclasses.map { |driver| driver.send(:base_url) }

# Without activesupport
driver_urls = (ObjectSpace.each_object(Webdrivers::Common.singleton_class).to_a - [Webdrivers::Common]).map { |driver| driver.send(:base_url) }
```

Which reduces the config a little to:

```rb
VCR.configure { |config| config.ignore_hosts(*driver_urls) }

WebMock.disable_net_connect!(allow_localhost: true, allow: driver_urls)
```

**Comment by titusfortner** [comment]
Ok, I just merged in code that will make `#base_url` public so that you don't have to use `#send`, I think that's all the support I want to provide for this in webdrivers gem at this time.

**Comment by eliotsykes** [comment]
Thanks @titusfortner!

Here's some code using the newly-public methods for anyone who stumbles on this issue and wants to know how to use them with VCR and WebMock:

```rb
# With activesupport gem
driver_urls = Webdrivers::Common.subclasses.map(&:base_url)

# Without activesupport gem
driver_urls = (ObjectSpace.each_object(Webdrivers::Common.singleton_class).to_a - [Webdrivers::Common]).map(&:base_url)

VCR.configure { |config| config.ignore_hosts(*driver_urls) }
WebMock.disable_net_connect!(allow_localhost: true, allow: driver_urls)
```

(I tried updating the [wiki page](https://github.com/titusfortner/webdrivers/wiki/Using-with-VCR-or-WebMock) but it looks like its not open for public edits.)

**Comment by kapoorlakshya** [comment]
Hi @eliotsykes, I have updated the wiki with the information you have provided - https://github.com/titusfortner/webdrivers/wiki/Using-with-VCR-or-WebMock

Let me know if anything can be improved. Thanks!

**Comment by titusfortner** [comment]
This is now available in 3.9.4

**Comment by titusfortner** [comment]
Also, ftr, I changed the wiki so that anyone can add to it.

**Comment by gnclmorais** [comment]
Hey folks, I’ve tried this but it didn’t work. `base_url` was giving me full URLs (like `https://chromedriver.storage.googleapis.com`) which was not allowing the requests.

However, extracting _just_ the host made it work:
```rb
driver_urls = Webdrivers::Common.subclasses.map do |driver|
  Addressable::URI.parse(driver.base_url).host
end
```

**Comment by cdmo** [comment]
@gnclmorais When I try and use `:selenium` I get an error because AWS is involved, so I had to do this:

```
driver_urls = Webdrivers::Common.subclasses.map do |driver|
  Addressable::URI.parse(driver.base_url).host
end << 'github-production-release-asset-2e65be.s3.amazonaws.com'
```

Feel like `github-production-release-asset-2e65be` probably isn't static, but, I had to add it because just using `s3.amazonaws.com` didn't work.
