### ISSUE TITLE
How to Use capybara with wedrivers

### ISSUE THREAD

**Issue by vbarnad** [titusfortner/webdrivers#111]
i am Replacing chromedriver with webdrivers with capybara.

* Operating system / CI Environment: MAC
* Browser and version: chrome 74

I am not sure how actually webdrivers will get installed if i check ~/.webdrivers
 i can only see a folder mac which is empty.

Any sample code will be helpful

**Comment by titusfortner** [comment]
There should be only two steps to make it work, documented here:
https://github.com/titusfortner/webdrivers/#usage

Let us know if you have any issues.

**Comment by vbarnad** [comment]
When i replace the code it does not launch the chrome and i get the error 
" unable to connect to chromedriver 127.0.0.1:9526 (Selenium::WebDriver::Error::WebDriverError)"

When i set debugger it shows as
"DEBUG Webdrivers Looking for Site: https://chromedriver.storage.googleapis.com"
