### ISSUE TITLE
Fails to start chrome on Mac because the filename contains spaces

### ISSUE THREAD

**Issue by dwt** [titusfortner/webdrivers#139]
#### Summary
When starting chrome through WebDrivers, WebDrivers asks the chrome binary for its version. This triggers an error as the google chrome binary contains spaces in its path on the Mac.

e.g. this will fail: 

```ruby
 `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --version`
```

To my understanding the problem is the in [system.rb:150](https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/system.rb#L150) or in [chrome_finder.rb:71](https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/chrome_finder.rb#L71) as it does not handle spaces in the path.

#### Debug Info
Please provide the following information for bug reports:

* Operating system / CI Environment: Mac OS 10.14.5
* Browser and version: Chrome Version 75.0.3770.90 (Offizieller Build) (64-Bit)

#### Expected Behavior
Space support in paths is required on Mac.

#### Actual Behavior
An error like

`*** Errno::ENOENT Exception: No such file or directory - /Users/dwt/Applications/Network/Browser/Google` is raised

**Comment by dwt** [comment]
My workaround was modifying the local file chrome_finder like this:

```ruby
      def mac_version(location)
        require 'shellwords'
        System.call("#{location.shellescape} --version")&.strip
      end
```

**Comment by kapoorlakshya** [comment]
Hi @dwt, I am unable to reproduce this in v4.0.1. I ran the specs on macOS 10.13.3 (w/ Ruby 2.4.6 and 2.6.3) with log level as `:debug` and I am seeing the path with spaces escaped:

```
2019-06-18 15:48:10 DEBUG Webdrivers making System call: //Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
2019-06-18 15:48:10 DEBUG Webdrivers Browser version: Google Chrome 75.0.3770.100
```

You can view the log here: https://travis-ci.org/kapoorlakshya/webdrivers/jobs/547300790#L242

**Comment by twalpole** [comment]
@dwt Are you manually specifying your Chrome location? What version of webdrivers are you using?

**Comment by kapoorlakshya** [comment]
I introduced this bug in v4.0.1 (#131). It's not escaping the user given path.

Will fix it under #138.

**Comment by dwt** [comment]
Ah, sorry, I removed that from the bug report because I thought it was irrelevant. Yes, I am manually specifying the location, and I also tried shell-escaping that location, but that doesn't work because then Selenium-WebDriver refuses to start chrome.

**Comment by dwt** [comment]
Out of interest, and because I'm not a ruby programmer by trade: I was wondering why you are using backticks to call out to the shell (thus to my understanding actually using a shell to execute those external commands). It seems to me that using a non-shell subprocess call like IO:popen would be a much safer way to call external tools - also not requiring any escaping of spaces in paths.

**Comment by kapoorlakshya** [comment]
@dwt Thanks for the suggestion. The gem now uses `IO.popen` to handle the system calls. Can you please load this gem from the `master` branch and confirm the fix works for you? Thanks!

```
# In Gemfile

gem 'webdrivers', git: 'https://github.com/titusfortner/webdrivers.git', branch: 'master'
```

**Comment by dwt** [comment]
> @dwt <https://github.com/dwt> Thanks for the suggestion. The gem now uses IO.popen to handle the system calls. Can you please load this gem from the master branch and confirm the fix works for you? Thanks!
> 
> # In Gemfile
> 
> gem 'webdrivers', git: 'https://github.com/titusfortner/webdrivers.git <https://github.com/titusfortner/webdrivers.git>', branch: 'master‘

This seems to work perfectly.

:-)

Best Regards,
Martin Häcker
