### ISSUE TITLE
MSWebdriver ignores currently installed version of Edge and fetches the latest available binary.

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/webdrivers#14]
I am already working on a PR to fix this, but submitting this here in case anyone runs into this issue.

Microsoft recently released a new webdriver version 6.17134 for Edge 17.17134. If you are using this gem to launch an older version, say 16.16299, Selenium will fail to launch the browser with this error:

```
#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:17556 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 17556)>
```

This is because v3.3.0 of this gem is downloading the latest version and ignoring the installed version of Edge.  The fix is to download the webdriver version that matches the installed version of Edge. I'll submit a PR to fix this. 

**Workaround**: Download the binary manually and or upgrade your Edge version.

**Comment by kapoorlakshya** [comment]
Submitted PR #15 to fix this.

**Comment by titusfortner** [comment]
PR #15 merged
