### ISSUE TITLE
WARN Selenium [DEPRECATION]

### ISSUE THREAD

**Issue by bit-of-a-shambles** [titusfortner/webdrivers#140]
#### Summary
Get lots of repeated deprecation errors. 

#### Debug Info
* Webdrivers version: 4.0.1
* Ruby version: 2.6.3p62
* Operating system / CI Environment: Macos
* Browser and version: Chrome 75.0.3770.100

#### Expected Behavior
No errors to show up

#### Actual Behavior
2019-06-19 13:15:57 WARN Selenium [DEPRECATION] Selenium::WebDriver::Error::ElementNotVisibleError is deprecated. Use Selenium::WebDriver::Error::ElementNotInteractableError (ensure the driver supports W3C WebDriver specification) instead.

I get this error repeatedly, any idea what could be causing it?

**Comment by titusfortner** [comment]
This is a Selenium issue, not a webdrivers issue:
See: https://stackoverflow.com/questions/56445641/ruby-watir-selenium-webdriver-depricated-warning/

**Comment by titusfortner** [comment]
Oh, just noticed you're already using Chrome 75. This is still a Selenium issue, please report the issue on that tracker with Selenium Version and a Stack trace. Thank you.

**Comment by twalpole** [comment]
The key part of that error is “ ensure the driver supports W3C WebDriver specification” - Did you happen to disable w3c mode in your driver?
