### ISSUE TITLE
Rake tasks not loaded if webdrivers gem is in the :test group

### ISSUE THREAD

**Issue by mattbrictson** [titusfortner/webdrivers#143]
#### Summary

I think this is mainly a documentation issue. The rake section of the README does not work with an out-of-the-box Rails 6 app, which is confusing.

Rails 6 ships with the webdrivers gem in the :test group, like this:

```ruby
group :test do
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end
```

In this default configuration, the rake tasks are not loaded unless the user explicitly specifies the test environment.

#### Debug Info

* Webdrivers version: 4.1.0
* Ruby version: 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
* Operating system / CI Environment: macOS 10.14.5
* Browser and version: N/A

#### Expected Behavior

I expect the rake instructions in the webdrivers README to work with an out-of-the-box Rails 6 app.

#### Actual Behavior

```
$ bundle exec rake webdrivers:chromedriver:update
rake aborted!
Don't know how to build task 'webdrivers:chromedriver:update' (See the list of available tasks with `rake --tasks`)
-e:1:in `<main>'
(See full trace by running task with --trace)
```

Possible workarounds:

**1. Explicitly specify the test environment**

```
$ RAILS_ENV=test bundle exec rake webdrivers:chromedriver:update
```

**2. Explicitly load webdrivers in the development environment**

```ruby
# Rakefile
require_relative 'config/application'

Rails.application.load_tasks

if Rails.env.development? && !defined?(Webdrivers)
  require "webdrivers"
  load "webdrivers/Rakefile"
end
```

**3. Load webdrivers in all environments**

Move `gem 'webdrivers'` out of the :test group and into the default group. However this is not desirable because the webdrivers gem has no reason to be installed or required in production. The :test group is the appropriate place for it.

**Comment by kapoorlakshya** [comment]
@mattbrictson Thanks for bringing this up. The `README` has been updated with option 1 under 6a0f482eb8f20fd5df12c0bf6734106c446fb22e.
