### ISSUE TITLE
if ENV["HOME"] is unset, then there's an error

### ISSUE THREAD

**Issue by jeremybmerrill** [titusfortner/webdrivers#158]
#### Summary
When `ENV['HOME']` is nil (as it is in my environment where Rails is running as a service and `webdrivers` is used outside of the test environment), all rake tasks fail, even non-`webdrivers` related ones.

The issue is that  ` DEFAULT_INSTALL_DIR = File.expand_path(File.join(ENV['HOME'], '.webdrivers'))` errors out. The issue is fixed by setting `HOME` manually (e.g. in my service def'n).

Presumably the fix would be to set some default path in case `HOME` isn't set.

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 4.12
* Ruby version: 2.6.5
* Operating system / CI Environment: Ubuntu

#### Expected Behavior
No error on `rake` even if `HOME` is unset or, less preferably, a clearer error message, noting that `webdrivers` expects `HOME` to be set.

#### Actual Behavior
````Nov 06 01:39:26 mycomputer rake[2445]: rake aborted!
Nov 06 01:39:26 mycomputer rake[2445]: TypeError: no implicit conversion of nil into String
Nov 06 01:39:26 mycomputer rake[2445]: /mypath/webdrivers-4.1.2/lib/webdrivers/common.rb:25:in `join'
Nov 06 01:39:26 mycomputer rake[2445]: /mypath/webdrivers-4.1.2/lib/webdrivers/common.rb:25:in `<module:Webdrivers>'
Nov 06 01:39:26 mycomputer rake[2445]: /mypath/webdrivers-4.1.2/lib/webdrivers/common.rb:11:in `<main>'
````

#### Thanks
Thank  you very much for developing `webdrivers`. It's clever and it has saved me some time futzing around and so I appreciate your work. :)

**Comment by kapoorlakshya** [comment]
@jeremybmerrill Thanks for reporting this.

I think `File.expand_path('~/.webdrivers')` will be better than relying on the ENV variable. I wasn't sure if it would work on Windows, but it surprisingly does:

```
irb(main):001:0> File.expand_path('~/.webdrivers')
=> "C:/Users/kapoorlakshya/.webdrivers"
```

**Comment by jeremybmerrill** [comment]
@kapoorlakshya I think that's probably right, but the ENV var is important to retain if someone, for some reason, wants to store the downloaded drivers somewhere other than `~/.webdrivers`.

**Comment by kapoorlakshya** [comment]
@jeremybmerrill That is already possible by pointing `Webdrivers.install_dir` to a custom location :)

**Comment by jeremybmerrill** [comment]
Oh, perfect!

Jeremy B. Merrill
