### ISSUE TITLE
Fails to find Chrome binary even though Brave is installed

### ISSUE THREAD

**Issue by nileshtrivedi** [titusfortner/webdrivers#159]
#### Summary
On Ubuntu 18.04 with webdrivers v4.1.3,  I had to install `chromium-browser` even though I already had `brave-browser` installed.

#### Debug Info

* Webdrivers version: 4.1.3
* Ruby version: 2.6.5p114
* Operating system / CI Environment: Ubuntu 18.04
* Browser and version: Version 0.70.122 Chromium: 78.0.3904.87 (Official Build) (64-bit)

# Error:

```
.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/webdrivers-4.1.3/lib/webdrivers/chrome_finder.rb:21:in `location': Failed to find Chrome binary. (Webdrivers::BrowserNotFound)
```

**Comment by kapoorlakshya** [comment]
@nileshtrivedi Only Google Chrome and Chromium (from chromium.org) are supported by default. You can make Brave work by pointing `Selenium::WebDriver::Chrome.path` to its binary as mentioned [here](https://github.com/titusfortner/webdrivers#chromechromium).

I tested with Brave on Windows and the correct `chromedriver` version was downloaded. Let me know if it doesn't work on Ubuntu and we can further troubleshoot this.

**Comment by kapoorlakshya** [comment]
Closing due to lack of response. Feel free to comment here if you run into problems.
