### ISSUE TITLE
Can't load rakefile (no rails)

### ISSUE THREAD

**Issue by RyanSpartan117** [titusfortner/webdrivers#160]
#### Summary
after adding
```
require 'webdrivers'
load 'webdrivers/Rakefile'
```
I get an error: `undefined method 'import' for main:Object (NoMethodError)`
#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 2.43
* Ruby version: 2.6.5
* Operating system / CI Environment: MACOS
* Browser and version: Chrome, 71-73

#### Expected Behavior
Able to load Rakefile then get the current chromedriver version.

#### Actual Behavior
Can't load the Rakefile in

**Comment by kapoorlakshya** [comment]
@RyanSpartan117 This might be a silly question, but do you have the `rake` gem included in your project?

I am also using `webdrivers` in a non-rails project and the `Rakefile` loads without errors.

**Comment by RyanSpartan117** [comment]
@kapoorlakshya Not a silly question - thanks for checking. I do have the `rake` gem in the project. Did you use the `load 'webdrivers/Rakefile` command?

**Comment by kapoorlakshya** [comment]
@RyanSpartan117 I added these two lines to my `Rakefile`:

```
require 'webdrivers'
load 'webdrivers/Rakefile'
```

And then I was able to see the rake tasks with `rake -T`.

**Comment by kapoorlakshya** [comment]
@RyanSpartan117 I just noticed you are using a really old version of the gem - 2.43. The rake tasks were added in v4, so give that a try.

**Comment by kapoorlakshya** [comment]
Closing due to lack of response. Feel free to comment here if you run into problems with the rake tasks in the latest version.

**Comment by RyanSpartan117** [comment]
Sorry for lack of reply. I ended up not needing the Rakefile in the end, so forgot to check back.

I have updated to 4.0, so hopefully it'll all work perfectly. I'm happy for this thread to be properly closed.

Thanks!
