### ISSUE TITLE
Update Nokogiri

### ISSUE THREAD

**Issue by OmriSama** [titusfortner/webdrivers#167]
#### Summary
Update Nokogiri to resolve CVE issues

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 4.2.0
* Ruby version: 2.5.7
* Operating system / CI Environment: Ubuntu, GitLab CI
* Browser and version: Chrome (latest, 80)

Hi. There's CVE issue with Nokogiri and it's causing our CI pipeline to fail, specifically in our bundler-audit stage.

![image](https://user-images.githubusercontent.com/10534779/75367988-f69b1d00-5875-11ea-8288-6ac2cda1fac9.png)

Webdrivers currently has the version of Nokogiri pinned. Would it be possible to update to the latest Nokogiri?

I've also opened a similar issue in the `xpath` repo: https://github.com/teamcapybara/xpath/issues/97

**Comment by luke-hill** [comment]
Nokogiri in master and 4.2.0 is only pinned to `~> 1.6` so nothing is stopping you upgrading nokogiri in the version you are using.

Run `bundle update nokogiri` and you're fine.
