### ISSUE TITLE
Edge on Mac

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/webdrivers#181]
We need to add support for using Microsoft Edge on a Mac.

**Comment by kapoorlakshya** [comment]
Hey @titusfortner, can you please remind me what's missing for macOS? I know we briefly discussed this over Slack, but I can't remember what exactly was said and chat history is not longer available. Based on my understanding, we already support all release versions and specs for `msedgedriver` are passing on macOS.

https://github.com/titusfortner/webdrivers/blob/06b2a4a3ce95f17b27c4678ecdcae3f78297b02b/lib/webdrivers/edge_finder.rb#L55-L60
