### ISSUE TITLE
Requiring webdrivers/geckodriver raises NameError

### ISSUE THREAD

**Issue by timcraft** [titusfortner/webdrivers#182]
#### Summary

Requiring webdrivers/geckodriver (as per the README) raises an exception.

#### Debug Info

* Webdrivers version: 4.4.1
* Ruby version: 2.7.1p83
* Operating system / CI Environment: macOS

#### Expected Behavior

No exception.

#### Actual Behavior

```
$ irb -r webdrivers/geckodriver
irb(main):001:0> Webdrivers::Geckodriver.update
Traceback (most recent call last):
...
NameError (uninitialized constant #<Class:Webdrivers::Network>::Net)
```

**Comment by kapoorlakshya** [comment]
@timcraft Thanks for reporting this bug. I'm able to reproduce it.

Will try to debug and push a fix this weekend.

**Comment by kapoorlakshya** [comment]
@timcraft The fix will be available in the next gem release.

**Comment by timcraft** [comment]
@kapoorlakshya Great, thank you!
