### ISSUE TITLE
Problem using the gem in docker inside WSL2

### ISSUE THREAD

**Issue by urubatan** [titusfortner/webdrivers#197]
https://github.com/titusfortner/webdrivers/blob/7ef83985ee9edf16de7599db60aad0e6df7d54c0/lib/webdrivers/system.rb#L152

This test to check WSL is causing problems if the gem is used inside docker at least if the server is executed in WSL2

**Comment by dirkkelly** [comment]
I am having the same issue, could we override this with an environment flag?

**Comment by kapoorlakshya** [comment]
Closed by #196. Fix confirmed to be working by @urubatan.
