### ISSUE TITLE
Add support for Microsoft Edge (chromium) builds for Linux once out of preview

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/webdrivers#198]
Preview builds are available as of Oct 2020 - https://blogs.windows.com/msedgedev/2020/10/20/microsoft-edge-dev-linux/

**Comment by kapoorlakshya** [comment]
Implemented this, but needs to be tested - https://github.com/kapoorlakshya/webdrivers/compare/master...198_200_m1_linux_msedgedriver

**Comment by kapoorlakshya** [comment]
Closed by a46c6fd547423ddc6de998331cb7c9a7d8a7aeab

**Comment by kapoorlakshya** [comment]
Reopened by e01704e529cbd296cb01a50fe7d4e084d05bc1f8:

> **Comment out support for msedgedriver on Linux until it's out of preview.**
>
> The linux driver version is in preview and not in sync with other operating systems. This means that the LATEST_RELEASE_ file is not usable for it. It has a separate _LINUX file AND the download file lives in a deferent location than the current `base_url`. This combination of differences makes it difficult to support Linux builds within the current implementation. I was able to make it sort of work, but the implementation was messy and seemed hack-ish. I think the best thing to do is to hold off on supporting Linux builds until the general release is available. It's currently in a preview release (insider) only.

**Comment by titusfortner** [comment]
It was reported that this works now, and it shouldn't matter for people not trying to use it, so I uncommented your code for 4.7.
