### ISSUE TITLE
Support for driver flags?

### ISSUE THREAD

**Issue by mockdeep** [titusfortner/webdrivers#209]
#### Summary

I have a bug that [appears to be with geckodriver](https://github.com/mozilla/geckodriver/issues/1862), but I'm not sure how to get flags through to the driver [per their documentation](https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md). Is there a way to pass flags to the driver for better logging?

* Webdrivers version: 4.6.0
* Ruby version: 2.6.6
* Operating system / CI Environment: Linux (CircleCI)
* Browser and version: Firefox 87.0

#### Expected Behavior

Tests run without issue.

#### Actual Behavior

Occasionally the *first* test to interact with the browser fails with:

```
Selenium::WebDriver::Error::UnknownError:
  Process unexpectedly closed with status 1
```

**Comment by titusfortner** [comment]
What code do you use to start your Selenium tests? You need to add log options to Firefox::Options instance as described in that geckodriver link. 
This is a Selenium question not an issue with the webdrivers code, so I'm closing the issue, but we can make sure you know where to pass in the info if you need more assistance.
