### ISSUE TITLE
Seems like an url for gecko driver download should be corrected 

### ISSUE THREAD

**Issue by ivarbanovv** [titusfortner/webdrivers#211]
#### Summary
I am using webdrivers 4.5.0 gem and whenever I try firing tests against a local firefox browser , I get the following error ` Webdrivers::NetworkError:
        Net::HTTPServerException: 404 "Not Found" with https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-macos.tar.gz`

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version:
* Ruby version: 4.5.0
* Operating system / CI Environment: MacOS Big Sur 11.2.1 (20D74)
* Browser and version: Firefox 87.0 (64-bit)

#### Expected Behavior
I expect `webdrivers` to download the proper version of Gecko 

#### Actual Behavior

I am using webdrivers 4.5.0 gem and whenever I try firing tests against a local firefox browser , I get the following error ` Webdrivers::NetworkError:
        Net::HTTPServerException: 404 "Not Found" with https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-macos.tar.gz`

digging into this , it seems that the issue is actually that Mozilla uploaded a `geckodriver-v0.29.1-macos.gz` file only for their `v0.29.1` instead of the usual `*.tar.gz` version

<img width="667" alt="Screenshot 2021-04-09 at 12 59 20" src="https://user-images.githubusercontent.com/5638198/114164337-d91efa80-9933-11eb-8076-e71bd1b7164a.png">

**Comment by mcoms** [comment]
Possible dupe of #210

**Comment by ivarbanovv** [comment]
Yep its a duplicate 😔 he beat me to it.

**Comment by titusfortner** [comment]
Thanks for the report, looks like geckodriver fixed the names.
