### ISSUE TITLE
Webdrivers library will not work with selenium 4.0.0

### ISSUE THREAD

**Issue by ibalosh** [titusfortner/webdrivers#219]
#### Summary
When you try to install webdrivers with bundler, with for example gemfile containing:

gem 'selenium-webdriver', '4.0.0'
gem 'webdrivers', '~> 4.6.1', require: false

it will not work, due limitation on https://github.com/titusfortner/webdrivers/blob/master/webdrivers.gemspec

From what I see versions up to 4 are supported. It does work with rc ones though.

**Comment by yahonda** [comment]
#218 would fix this issue.

**Comment by ibalosh** [comment]
thanks @yahonda

**Comment by titusfortner** [comment]
4.7 has been released! Let me know of any issues with it.
