### ISSUE TITLE
rails tasks are not being found

### ISSUE THREAD

**Issue by weedySeaDragon** [titusfortner/webdrivers#223]
#### Summary
When I run `bundle exec rails -T webdrivers`  no webdrivers tasks are listed.
They're not listed even if I run `bundle exec rails -T -A`

It works (the tasks are found) if I add these lines into the `Rakefile` of my Rails project:
```
require 'webdrivers'
load 'webdrivers/Rakefile'
```
I found that suggestion in this old closed issue: #160 

#### Debug Info
I found the problem exists with 2 of the projects I'm working on; I also tested with webdrivers 5.0.0

* Webdrivers version: 4.6.1, 4.7.0, 5.0.0
* Ruby version:  2.6.6, 2.7.4
* Operating system / CI Environment: macos 11.6
* Browser and version:  n/a

Rails versions  6.1.4.1, 5.2.6

#### Expected Behavior
All webdrivers tasks defined in the  webdrivers gem `webdrivers/lib/tasks/*.rake` files should be listed.

#### Actual Behavior
no tasks are listed

**Comment by kapoorlakshya** [comment]
@weedySeaDragon Can you take a look at this StackOverflow [post](https://stackoverflow.com/a/36075566) and see if that's what you're running into? The railtie support still exists [here](https://github.com/titusfortner/webdrivers/blob/main/lib/webdrivers/railtie.rb) and *should* be working.

**Comment by kapoorlakshya** [comment]
Closing due to lack of response.

**Comment by zalom** [comment]
> @weedySeaDragon Can you take a look at this StackOverflow [post](https://stackoverflow.com/a/36075566) and see if that's what you're running into? The railtie support still exists [here](https://github.com/titusfortner/webdrivers/blob/main/lib/webdrivers/railtie.rb) and _should_ be working.

@kapoorlakshya, I had the same issue on Rails 7.0.5 and Ruby 3.1.2.
Rake tasks were listed only when I do this ->
```ruby
# test/test_helper.rb
require 'webdrivers'
```
and
```ruby
# Rakefile
load 'webdrivers/Rakefile'
```
