### ISSUE TITLE
GitHub says latest release is v4.5, but lib/webdrivers/version.rb shows 5.0.0

### ISSUE THREAD

**Issue by mileslane** [titusfortner/webdrivers#224]
I ran `bundle update webdrivers` and got webdrivers 5.0.0 installed. I am just confused why that would happen if the new version hasn't been released yet.

**Comment by kapoorlakshya** [comment]
@mileslane You have the right (latest) version. We're just behind on updating our tags/releases on GitHub, which I'll try to do soon™
