### ISSUE TITLE
Cannot reach site for GheckoDriver

### ISSUE THREAD

**Issue by ghost** [titusfortner/webdrivers#23]
Hello,

Using the gem I am able to get chromedriver working. chrome.current, chrome.latest etc all return expected results. Using ff = Webdrivers::Geckodriver, ff.current == nil, ff.latest == Can not reach site.

Is there more documentation out there for installing and updating the drivers? I am missing something?

**Comment by kapoorlakshya** [comment]
You don't need to do anything to get the latest webdriver binaries - the gem does it for you as soon as you launch the browser. Can you please update to the latest version (if needed), set the logger to `:debug` using `Webdrivers.logger.level = :debug` and then paste the output here?

**Comment by titusfortner** [comment]
Adding this should "just work" : `require 'webdrivers'`

If you need to specify something more for some reason (in the watirspecs I want to specifically log something)
```
require 'webdrivers'
Webdrivers::Chromedriver.update
```
