### ISSUE TITLE
NoMethodError: undefined method `match' for nil:NilClass

### ISSUE THREAD

**Issue by nicwillemse** [titusfortner/webdrivers#24]
```
[1] pry(main)> require 'webdrivers'
=> true
[2] pry(main)> Webdrivers::Chromedriver.current
rails_console: No such file or directory - /root/.webdrivers/chromedriver
NoMethodError: undefined method `match' for nil:NilClass
from /usr/local/bundle/gems/webdrivers-3.4.3/lib/webdrivers/chromedriver.rb:12:in `current'
```
Same error when running tests.
interestingly the directory '/root/.webdrivers/chromedriver' does exist.

ruby version : 2.5.3
os:  alpine

**Comment by haniqassim** [comment]
Same problem here

**Comment by kapoorlakshya** [comment]
Can you check if you are able to manually retrieve the version from the binary using `/root/.webdrivers/chromedriver --version`? Also, which version of Chrome are you using?

Another thing that'll help us troubleshoot this is setting the logger level to `:debug` using `Webdrivers.logger.level = :debug` and then attempting to launch Chrome. Please paste the output here.

**Comment by mascolim** [comment]
Try deleting chromedriver in .webdrivers and running again. Before 1.4.1 webdrivers pulled chromedriver 70.xxx.xxx which didn't match the regex which failed when reading the current webdriver. Deleting the webdriver or merging #21 may fix the error if it is the same one.

**Comment by titusfortner** [comment]
Webdrivers does not currently support the `7\d\.\d+` syntax. If you are having an issue with this you can update to the latest gem and specify the specific version you want: `Webdrivers::Chromedriver.version = 2.45`
