### ISSUE TITLE
Use chromedriver provided by electron for linux/arm64

### ISSUE THREAD

**Issue by ayufan** [titusfortner/webdrivers#242]
#### Summary
Chrome officially releases ChromeDriver only for linux/amd64, macos/amd64 and macos/arm64. There's no chrome driver for linux/arm64. This disallows using `webdrivers` on linux arm64.

The `webdrivers` could temporarily for `linux/arm64` use official releases provided by Electron in a transition period: https://github.com/electron/electron/releases/tag/v21.2.0. They provide up-to date chromedrivers built for all architectures.

If there would be an interest in such feature, I would happily contribute it.

**Comment by titusfortner** [comment]
Ah, interesting, I didn't realize electron distributed their own binaries. Would be great to add it.

Though, something to keep in mind, the Selenium team is working to develop a driver/browser manager — "[The Selenium Manager](https://github.com/SeleniumHQ/selenium/tree/trunk/rust)" — that will be integrated directly into the Selenium code and hopefully remove the need for 3rd party managers entirely. Hopefully beta version of it will be released in Selenium 4.6 tomorrow.

If you're interested in working on this feature and don't mind Rust, implementing it there will benefit Selenium users in all languages. Come find us in [Selenium Slack](https://www.selenium.dev/support/#ChatRoom) #selenium-tlc channel to discuss if you'd like.

**Comment by ayufan** [comment]
Thanks. I will come around and see how I could help :)

**Comment by titusfortner** [comment]
@ayufan out of curiosity have you had any issues using the x86 version of the drivers on ARM architecture? Reports I've gotten seem that it works? Theoretically if something isn't working, Google should be providing a compatible binary instead of our needing to use electron. Just checking.

**Comment by titusfortner** [comment]
I'm going to close this as out of scope.
