### ISSUE TITLE
Fix chromedriver renaming issue for M1 on Selenium 3.x

### ISSUE THREAD

**Issue by tchiaspko** [titusfortner/webdrivers#243]
#### Summary
Can we get a patch for this issue but for people who are still stuck on selenium 3.x ? 
https://github.com/titusfortner/webdrivers/issues/237

According to the changelog at https://github.com/titusfortner/webdrivers/blob/main/CHANGELOG.md#500-2021-10-19, webdriver 5.x requires selenium 4.x. I am still using     webdrivers (4.6.1) which is only about one year old. 

It is not easy to migrate from selenium 3.x to 4.x so it would be better to backport https://github.com/titusfortner/webdrivers/issues/237 for the people who are still using selenium 3.x 

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version:
* Ruby version:
* Operating system / CI Environment:
* Browser and version:

#### Expected Behavior
What you expect to happen.

#### Actual Behavior
What is actually happening: Error message, stack trace, DEBUG log if applicable (set `Webdrivers.logger.level = :DEBUG` after you require webdrivers)

**Comment by kapoorlakshya** [comment]
@tchiaspko Your best bet would be to monkey patch `webdrivers` in your code and override `Chromedriver#driver_filename` with the definition from #239. If multiple users end up requesting this, we would consider creating a new v4 release, but I don't have time right now unfortunately.

**Comment by titusfortner** [comment]
This code is using features in Selenium 4, and we don't want to maintain multiple code bases.

Moving to Selenium 4 should be pretty easy if you aren't using deprecated capabilities (which should both be easy to fix and be better conform to what modern drivers expect).
