### ISSUE TITLE
Feature: Allow user to define a target_version which overrides the latest version.

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/webdrivers#25]
Current implementation fetches the latest webdriver binary if `current` does not match `latest`. The user may not want this to happen if they're executing their tests against a specific (older) version or versions of the browser.

**My use case**: I am working on debugging an issue which requires me to test prior versions of `selenium-webdriver` and corresponding binaries for IE. To make this work, I have to remove `webdrivers` gem and manually place the binary for each version in `PATH` and test my code.

Through this feature, the user will be able to provide a `target_version` (open to a better name) which overrides `latest` and downloads the user given version of the binary.

**Example**

```
require 'watir'
require 'webdrivers'

Webdrivers::IEdriver.target_version = 3.14.0.0

b = Watir::Browser.new :ie

Webdrivers.IEdriver.current = #<Gem::Version "3.14.0.0"> # matches target_version
Webdrivers.IEdriver.latest = #<Gem::Version "3.141.0.0"> # latest version, newer than target_version
```

I'm interested in submitting a PR for this. Just want to see if anyone has an opinions or recommendations.

**Comment by titusfortner** [comment]
This is supported now: 

```
Webdrivers::Chromedriver.version = 2.29
```

aa01fd92ff807320bca0334cd596558d1c60d447

**Comment by kapoorlakshya** [comment]
Thanks, @titusfortner!
