### ISSUE TITLE
way to configure "get latest version even if it doesn't match chrome" ?

### ISSUE THREAD

**Issue by josh-m-sharpe** [titusfortner/webdrivers#250]
Your attempt to solve this problem is admirable.  👏 👏 !@#$ Google 👏 👏 

As of this writing `https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb` is 115.0.5790.110
There is no 115.0.5790.110 here: https://chromedriver.chromium.org/
or here: https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

I can 'fix' this by manually hardcoding 114:

`Webdrivers::Chromedriver.required_version = '114.0.5735.90'` - which does exist

...and seemingly works so far?  But it'll jsut break in a few weeks when 116 comes out and 114 isn't compatible with that.. or something.

Seems it would be good if I can just tell webdrivers to get the latest version available since that's sorta what the .deb above provides?

Maybe? I dunno? Thoughts?

!@#$ Google.

ruby 3.2 something
webdrivers 5.2.0

**Comment by titusfortner** [comment]
No! Chrome for Testing is going to allow us to do some great things like automatic browser downloads! It's just caused some hiccups we weren't expecting or prepared for in the short term. 😞 

I sketched out the current recommendations and my proposed plans here — https://github.com/titusfortner/webdrivers/pull/251

Let me know what you think.
