### ISSUE TITLE
Latest Google Webdriver update breaking changes

### ISSUE THREAD

**Issue by theprogramsam** [titusfortner/webdrivers#252]
#### Summary
Google recently change how the webdrivers are found and located. With the most recent version of chrome, it fails.

#### Debug Info
Please provide the following information for bug reports:

* Webdrivers version: 5.2.0
* Ruby version: 3.1.2
* Operating system / CI Environment: MacOS M1
* Browser and version: Chrome 115.0.5790.102

#### Expected Behavior
Downloads and uses the correct chrome webdriver

#### Actual Behavior
What is actually happening: Error message, stack trace, DEBUG log if applicable (set `Webdrivers.logger.level = :DEBUG` after you require webdrivers)

```
Webdrivers::NetworkError:
  Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/115.0.5790.102/chromedriver_mac_arm64.zip
```

References:
https://googlechromelabs.github.io/chrome-for-testing/#stable
https://chromedriver.chromium.org/downloads/version-selection
https://stackoverflow.com/questions/76562584/unable-to-find-the-latest-chrome-driver-114-0-5735-134

**Comment by theprogramsam** [comment]
looks like this PR may be related? https://github.com/titusfortner/webdrivers/pull/249

**Comment by titusfortner** [comment]
Yes, the long conversation about what happened and why is in #247, summary and recommendations and proposed plans are in #251
