### ISSUE TITLE
Unable to install the latest version of update selenium-webdriver

### ISSUE THREAD

**Issue by zmariscal** [titusfortner/webdrivers#257]
#### Summary
Due to how `webdrivers.gemspec` is setup:

```
  s.add_runtime_dependency 'selenium-webdriver', '~> 4.0', '<= 4.11'
```

This only lets us to get the version `4.10.0 `

#### Debug Info
N/A

#### Expected Behavior
We should be able to get the latest version of `selenium-webdriver` `4.11`

#### Actual Behavior
We can only fetch `4.10` of `selenium-webdriver`

**Comment by titusfortner** [comment]
If you can use Selenium 4.11, you shouldn't be using this gem. https://github.com/titusfortner/webdrivers#update-future-of-this-project
