### ISSUE TITLE
Rake Tasks for Update & Remove

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/webdrivers#28]
Webdrivers gem should support a means for deleting binary without requiring the user to `rm -rf ~/.webdrivers`

**Comment by twalpole** [comment]
If providing this I think it should a rake task rather than a public API code method

**Comment by titusfortner** [comment]
I implemented `#remove` a long time ago, so I'm not sure what this was about, but we can track the Rake tasks with it now.
