### ISSUE TITLE
Checking latest Chromedriver version via LATEST_RELEASE is deprecated

### ISSUE THREAD

**Issue by jkotests** [titusfortner/webdrivers#31]
From https://github.com/flavorjones/chromedriver-helper/issues/79, using Chromedriver's LATEST_RELEASE page for the latest version is deprecated.

We currently get 2.46, even though the latest is now 73.0.3683.68. Both support Chrome v73, so not a big deal. However, when Chrome v74 is released, we will presumably run into version mismatch errors (ie we'd still be downloading 2.46).

We need to update the process as documented in http://chromedriver.chromium.org/downloads/version-selection.

**Comment by kapoorlakshya** [comment]
Hi @jkotests, I have submitted PR #32 if you'd like to review it when you get a chance.

**Comment by kapoorlakshya** [comment]
Closed by #32.
