### ISSUE TITLE
Public Methods

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/webdrivers#36]
Let's make sure that browser versions and driver versions are properly and usefully publicly accessible

**Comment by kapoorlakshya** [comment]
As discussed on Slack, these would be useful to have for all supported browsers:

```
#
# Returns installed browser version
#
Webdrivers.chrome.version 

#
# Returns current webdriver version
#
Webdrivers.chrome.driver_version 

#
# Returns ~/.webdrivers/chromedriver or user given path
#
Webdriver.chrome.driver_path
```

And maaaaybe.... `Webdrivers.chrome.latest_driver_version` to easily compare what you have vs latest available for download.

**Comment by titusfortner** [comment]
What we have now:
`#update`
`#remove`
`#download` --> This can be made private, there's no reason to download independent of updating

`#version` (requested version)
`#latest_version` (network call to lookup)
`#desired_version` (either requested or latest) --> This can be made private, users don't need this
`#current_version` (what is on the system)

`#install_dir`
`#binary` (relies on `#install_dir`)

`#windows_version` (MSWebdriver only)

So as to the specifics referenced:
`Webdrivers.chrome.version` ==> we can do `Webdrivers::Chromedriver.chrome_version` if we make the private `#chrome_version` a public method

`Webdrivers.chrome.driver_version ` ==> this is the same as `Webdrivers::Chromedriver.current_version ` 

`Webdrivers.chrome.driver_path` ==> this is the same as `Webdrivers::Chromedriver.binary `; `#driver_path` probably makes more sense than `#binary`, so maybe we should rename it.

**Comment by kapoorlakshya** [comment]
`version` and `current_version` seem synonymous and could cause confusion at first look. Maybe it'll be more intuitive if we replace `versions` with `desired_version` as the public method? Then we'll have `desired_version` (what the user wants) and `current_version` (what the user has).

**Comment by titusfortner** [comment]
00ebdc2b6a3aec11b99d8fd3bfec0d98cb8d3137
