### ISSUE TITLE
Locate Chrome the same way as Google

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/webdrivers#45]
Here is Google's code for how they get the default browser.
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/chrome/chrome_finder.cc
This won't be an issue in 99% of cases, but it is possible that the webdrivers method and the chromedriver method can each get different information resulting in the wrong driver being used.

**Comment by blerner** [comment]
I *think* this issue pops up in more than 1% of cases: if I'm understanding correctly, then any Linux machine that has only Chromium installed but not Chrome, will wind up triggering the symptoms shown in #67.  This doesn't seem like too implausible a configuration...  As in #67, setting the path manually avoids the issue, but only on my machine: some of my colleagues have Chrome installed but not Chromium, and so the "fix" for me actually breaks things for them, which makes it annoyingly hard to get consistent test run behavior.

**Comment by titusfortner** [comment]
@blerner To clarify, you are saying that Chromedriver itself picks the correct browser on the system, but webdrivers gem does not?

**Comment by blerner** [comment]
Until earlier today, I was using the gems `capybara`, `capybara-webkit`, `selenium-webdriver`, and `chromedriver-helper`, I set `Capybara.default_driver = :selenium_chrome_headless`, and everything worked fine.  Today I saw the deprecation notice for `chromedriver-helper`, and that the recommended update was to `webdrivers`.  So I replaced `selenium-webdriver` and `chromedriver-helper` with `webdrivers`, and everything broke.  Then I set the `Selenium::WebDriver::Chrome.path`, and things worked again.  That's the entirety of my current `git diff` relative to this morning.

If I'm doing something stupid, I'm happy to fix it.  But as far as I can tell, yes: chromedriver worked with Chromium, and webdrivers does not.

**Comment by titusfortner** [comment]
No, the issue is that with later versions of chrome you need to match the driver version to the browser version. So a driver manager needs to know the browser version to ensure correct driver version. Webdrivers is currently just looking for google-chrome and just looking on PATH. Just looked at the chromedriver code again, it isn't even looking on PATH, and looks for a bunch of different things.

I don't want people to have to specify their browser location. We need to do more, even if we don't get it exactly the same. I'll add this as a requirement for 4.0 release.
