### ISSUE TITLE
Test on Ruby 2.5 and 2.6 as well

### ISSUE THREAD

**Issue by connorshea** [titusfortner/webdrivers#46]
Currently the .travis.yml only tests on Ruby 2.4 and JRuby 9.2, it'd probably be good to run the test suite on Ruby 2.5 and 2.6 as well :)

https://github.com/titusfortner/webdrivers/blob/024b60a73ad7b1a004e8e2b8c35c31a2753757dc/.travis.yml#L1-L14

**Comment by kapoorlakshya** [comment]
Hi @connorshea, I plan to adding them in my next PR including the performance improvements.
