### ISSUE TITLE
Unable to find chromedriver

### ISSUE THREAD

**Issue by robbymarston** [titusfortner/webdrivers#48]
I'm using Capybara and Selenium for testing; however, my specs are failing with the following error: 

```
Selenium::WebDriver::Error::WebDriverError:
             Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

Here is my configuration:

**/Gemfile**
```
...
gem 'webdrivers', '~> 3.0'
...
```

**/spec/spec_helper.rb**
```
...
require 'webdrivers' 
require 'selenium-webdriver'

Capybara.register_driver :chrome_headless do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('--headless')
  options.add_argument('--no-sandbox')
  options.add_argument('--disable-dev-shm-usage')
  options.add_argument('--disable-gpu')
  options.add_argument('--window-size=1400,1400')
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: options)
end

Capybara.javascript_driver = :chrome_headless
Capybara.default_host = Domain.manager_domain

Capybara.configure do |config|
  config.default_max_wait_time = 15 # seconds
end
...
```

I've noticed that `~/.webdrivers` does not exist, I'm assuming that's an issue. I'm not sure when the drivers are supposed to download/install, but it appears as though they're haven't.

**Comment by genius-ua** [comment]
In your project:

require 'webdrivers'

**Comment by robbymarston** [comment]
> In your project:
> 
> require 'webdrivers'

I have this in **/spec/spec_helper.rb** already, does that not suffice? If not, what file would you recommend I add that line to?

**Comment by kapoorlakshya** [comment]
Hi @robbymarston, it should work from `spec_helper.rb`. The webdriver is downloaded when you invoke the browser launch method as long as you don't have a driver path already defined in Selenium. See [here](https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/selenium.rb#L7).

You said `~/.webdrivers` does not exist. Could it be a permissions issue (if on Windows)? Please try the following and share the results:

1. Set `Webdrivers.install_dir` to a folder within your project and rerun the spec(s).
2. Set log level to debug and share the output: `Webdrivers.logger.level = :DEBUG`

**Comment by robbymarston** [comment]
The issue was me explicitly requiring selenium-webdriver. Apparently, webdrivers overrides the `Selenium:WebDriver:Chrome` method in [lib/webdrivers/selenium.rb](https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/selenium.rb). When I required it, I essentially reverted the method to its original state...which obviously does not call `WebDrivers.Chrome.update` on thusly download the driver. May be worth mentioning in the README; although, it's pretty edge-casey. Thanks everyone for your help!
