### ISSUE TITLE
Don't depend on net_http_ssl_fix

### ISSUE THREAD

**Issue by ioquatix** [titusfortner/webdrivers#59]
This should be optional, not required. I suggest adding a note in the README for users who want to use it. Otherwise, I see this as a major security risk.

**Comment by kapoorlakshya** [comment]
Hi @ioquatix, could you please expand on why you see `net_http_ssl_fix` as a major security risk? `webdrivers` doesn't automatically load it. The user has to explicitly require it using `#net_http_ssl_fix`, similar to what you're suggesting in the README (#60).

**Comment by ioquatix** [comment]
It's a major security risk because it replaces system `cacert.pem` in a very casual way. The fact that it even showed up gave me enough concern to check it out.

I don't even want such a gem in my code base. You should make the effort proportional to the risk. Having documentation about how to deal with Windows is okay. It's literally two lines:

```ruby
gem "net_http_ssl_fix"

require "net_http_ssl_fix"
```

Additionally, at a broader level, this gem is not the right place to solve this problem, it should be solved by fixing Windows. If Windows has crappy default certificates, maybe there is a better fix within the OS itself.

**Comment by kapoorlakshya** [comment]
Got it. Thanks for the explanation.

As someone who maintains multiple Windows test nodes, those SSL errors could definitely be a pain. Based on my experiences, I was glad `webdrivers` provided an automated solution. However, I can now see why you wouldn't want a SSL related gem forced into your code base, especially if you're not a Windows user.

I'm okay with merging your PR. I'll wait until Monday to see if Titus has any comments.

**Comment by ioquatix** [comment]
I'm really happy you are taking the time to review this PR seriously!

**Comment by ioquatix** [comment]
If you need to isolate this to Windows, I suggest doing something like: https://albertogrespan.com/blog/installing-platform-specific-gems-with-bundler/

**Comment by titusfortner** [comment]
Did this actually get a PR? I'm not seeing it in the list.

I agree it is probably smarter to let Windows users do this themselves if it is an issue with a note in the README. Do we want to go further and tell users in the README that while it is probably the easiest solution, it might not be the best solution?

Thanks for the input!

**Comment by connorshea** [comment]
Can we get a new release to remove this dependency? :) I was similarly concerned by the dependency.

**Comment by kapoorlakshya** [comment]
Hi @connorshea, that's on my to-do list for this week.
