### ISSUE TITLE
Don't redefine methods

### ISSUE THREAD

**Issue by ioquatix** [titusfortner/webdrivers#61]
```
bundler/gems/webdrivers-ec5a9d9d5e03/lib/webdrivers/selenium.rb:6: warning: method redefined; discarding old driver_path
gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/chrome.rb:34: warning: previous definition of driver_path was here
bundler/gems/webdrivers-ec5a9d9d5e03/lib/webdrivers/selenium.rb:12: warning: method redefined; discarding old driver_path
gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/firefox.rb:51: warning: previous definition of driver_path was here
bundler/gems/webdrivers-ec5a9d9d5e03/lib/webdrivers/selenium.rb:18: warning: method redefined; discarding old driver_path
gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/edge.rb:33: warning: previous definition of driver_path was here
bundler/gems/webdrivers-ec5a9d9d5e03/lib/webdrivers/selenium.rb:24: warning: method redefined; discarding old driver_path
gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/ie.rb:30: warning: previous definition of driver_path was here
```

Does this gem monkey patch selenium?

Is there a better way to do it?

If not, then can use `undef driver_path` first.

**Comment by kapoorlakshya** [comment]
Yeah, it does - https://github.com/titusfortner/webdrivers/blob/master/lib/webdrivers/selenium.rb

`undef driver_path` should do it. The only other, less ideal way I can think of is asking the users to define the driver path(s) in their project. Will defer to @titusfortner on this.

**Comment by ioquatix** [comment]
Does `Webdrivers::Chromedriver.update` actually do anything? I'm assuming you are downloading the web driver executable on demand and that's the entry point to do so?

**Comment by kapoorlakshya** [comment]
> I'm assuming you are downloading the web driver executable on demand and that's the entry point to do so?

It is the entry point for automatic updates. You could call it in your project to trigger an on-demand update check, but it is not required.

**Comment by ioquatix** [comment]
Right, but calling `driver_path` invokes `#update` which will download the required files. The point is, it only downloads the files when calling `driver_path` which is invoked from the `Selenium::Webdriver::$Browser#initialize`. Otherwise, you could just write `Selenium::Webdriver::Chrome.driver_path = Webdrivers::Chrome.update` or whatever it is. You don't want to force users to download binary they aren't going to use.

**Comment by kapoorlakshya** [comment]
> You don't want to force users to download binary they aren't going to use.

In what case would a user not use the downloaded driver binary?

**Comment by ioquatix** [comment]
If I'm on a mobile connection I don't want to download files I'm not planning on using.

**Comment by kapoorlakshya** [comment]
> don't want to download files I'm not planning on using.

This at first makes it sound like you don't want to download a driver at all. But I am not sure how you'll interact with the browser without a driver. So let me confirm what I think you're implying - you basically want to disable automatic/forced update checks if you're on mobile or for whatever other reasons. Is that right?

P.S. I'm new to the dev side of selenium and drivers, so please feel free to share what the big picture is and what I'm missing here.

**Comment by ioquatix** [comment]
The main issue here is to avoid printing warnings due to redefining methods.

`undef` is one way, but another way is use the setters that are given, e.g. https://github.com/SeleniumHQ/selenium/blob/2abd80f236d1a7459ef638e96af8c4efd86b4abd/rb/lib/selenium/webdriver/chrome.rb#L31-L34

In order to do this, you'd need to do something like:

```ruby
require 'webdrivers/chrome'
WebDrivers::Chrome.use! # Fetch the chrome driver, and invoke Selenium::WebDriver::Chrome.driver_path=
```

**Comment by kapoorlakshya** [comment]
Thank you for the code example! I agree, that does look like a good approach to avoid the warnings. I'm adding this to the [v4 milestone](https://github.com/titusfortner/webdrivers/milestone/1).

**Comment by titusfortner** [comment]
We shouldn't need the monkey patches, they were just the easiest way to get it working. @kapoorlakshya this is one of the things I brought up with you in a PM that we should fix, I just didn't add it to our milestones. :)

Thanks @ioquatix for the input on this.

**Comment by titusfortner** [comment]
Of note though, automatic updates will still be the default when the driver is called. If you do not want to get an update, you need to explicitly set your desired version.

Actually, that's why we did monkey patch so that we didn't need to use a shim or do the update when required, and wait until the specific service class was initialized. I'll have to think if there's a good alternative here. Maybe we can add a hook to selenium to extend this.

**Comment by titusfortner** [comment]
As of webdrivers 3.8.0, if you are using Selenium 3.151.59 or higher, it will call a proc rather than requiring the monkey patch.
