### ISSUE TITLE
Provide a standalone way to update the drivers.

### ISSUE THREAD

**Issue by kapoorlakshya** [titusfortner/webdrivers#65]
`chromedriver-helper` provides a standalone way to update the drivers. We should consider doing that as well.

```ruby
update-chromedriver
update-geckodriver
update-iedriver
update-mswebdriver
```

See https://github.com/flavorjones/chromedriver-helper#standalone.

**Comment by rylanb** [comment]
In the docs it shows that you can run: `Webdrivers::Chromedriver.update` would that not be enough?

**Comment by kapoorlakshya** [comment]
You'll have to call that from your project code though. Something like `update-chromedriver` will let us  download/update the driver(s) from the terminal.

Just one of the features that `webdrivers` could provide for users coming from `chromedriver-helper`.

**Comment by kapoorlakshya** [comment]
Now that I think more about this, we don't need this feature. Users can lock down the driver version if they do not want automatic updates and then call `#update` from `irb` or in their project as needed.
