### ISSUE TITLE
Documentation: Update typo in wiki for VCR configuration

### ISSUE THREAD

**Issue by martinbjeldbak** [titusfortner/webdrivers#66]
I am unable to update the wiki so please find description of change request in this issue.

Issue: The `ignore_hosts` call for VCR configuration is a method that takes an array and not an assignment.

The error is on this wiki section: https://github.com/titusfortner/webdrivers/wiki/Using-with-VCR-or-WebMock#vcr

It should be

```ruby
VCR.configure do |config|
  config.ignore_hosts([
    "chromedriver.storage.googleapis.com",
    "github.com/mozilla/geckodriver/releases",
    "selenium-release.storage.googleapis.com",
    "developer.microsoft.com/en-us/microsoft-edge/tools/webdriver"
  ])
end
```

See here for example usage: https://github.com/vcr/vcr/blob/806dcebfd87123b45cb57c2152be568030864c4b/spec/support/shared_example_groups/hook_into_http_library.rb#L553

**Comment by kapoorlakshya** [comment]
Thanks, @martinbjeldbak! I have updated the wiki.

**Comment by martinbjeldbak** [comment]
@kapoorlakshya apologies, I've done some more playing around and it turns out it has to be a list of arguments, not an array

```ruby
VCR.configure do |config|
  config.ignore_hosts(
    "chromedriver.storage.googleapis.com",
    "github.com/mozilla/geckodriver/releases",
    "selenium-release.storage.googleapis.com",
    "developer.microsoft.com/en-us/microsoft-edge/tools/webdriver"
  )
end
```

**Comment by kapoorlakshya** [comment]
No problem! Updated it.
