### ISSUE TITLE
log version of chromedriver being used?

### ISSUE THREAD

**Issue by jrochkind** [titusfortner/webdrivers#73]
I believe that without updating my version of `webdrivers` in `Gemfile.lock`, I can still get a different version of (eg) chromedriver on machine-to-machine or run-to-run? Because it will download the most recent if not cached?

I am getting a travis CI failure, perhaps due to changed chromedriver. It's a frustrating one to debug because I'm not getting it locally. 

1. Should webdrivers automatically print out the version of a driver it's using? That would make it easier for me to compare the chromedriver version from a lot of an old travis run that worked, to a log of the more recent one that did not. To see if that is the difference that's giving me a failure. As it is,  the version of chromedriver being used in my historical succesful tests seems lost to history. 
  * If there's a way for me to manually get this to happen, I could add it to my code now (and will do so if I can figure out how), but of course it's too late to add it to historical runs. I wonder if it should be output by default because by the time you know you need it...

2. On local workstation where my tests are green... is it possible webdrivers is using a cached copy, instead of the same copy it's downloading fresh on travis?  If so... how do I uncache it, to make it more like travis?  It's possible this is in the README, but i was having trouble finding it. Or I may be misunderstanding what's going on.

**Comment by kapoorlakshya** [comment]
@jrochkind I followed https://github.com/sciencehistory/scihist_digicoll/pull/114 and looks like you've already figured out that the failure is specific to Chrome v74 on Travis. I'll go ahead and answer your questions anyway:

1. The current version is logged to `DEBUG` level. 

2. You can log it in your project with:

```ruby
Webdrivers::Chromedriver.current_version.to_s
#=> "73.0.3683.68"
```

I'll add this info to the README soon.

3. `webdrivers` downloads `chromedriver` based on the Chrome/Chromium version on your system. Based on your findings, local had Chrome 73 and Travis was downloading Chrome 74. This means that Chrome and `chromedriver` 73 vs 74 was causing the difference in the test results.

Hope this helps.

**Comment by jrochkind** [comment]
Thank you, very helpful!

**Comment by jrochkind** [comment]
(I think it's a bug in Chromedriver 74, but don't have the energy to figure out how/where to report it!)

**Comment by kapoorlakshya** [comment]
> where to report it!

See http://chromedriver.chromium.org/help.

**Comment by jrochkind** [comment]
Thanks! Tried to do my duty. :) https://groups.google.com/forum/#!topic/chromedriver-users/0Pu-TPvlu18
