### ISSUE TITLE
Don't delete existing driver if there's nothing to replace it with. 

### ISSUE THREAD

**Issue by shepmaster** [titusfortner/webdrivers#8]
Due to #7, a working installation stopped working because the driver binary was removed, even though there was no suitable replacement. In such cases, it would be better to not remove the existing driver.

**Comment by boris-petrov** [comment]
@titusfortner - this would be very nice indeed. Can you please take a look at it?

**Comment by titusfortner** [comment]
3.2.4 should fix this. Let me know if it doesn't.
